//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizadores()
        {
            this.Mensagens = new HashSet<Mensagens>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public byte[] SaltedPassword { get; set; }
        public Nullable<int> userImage { get; set; }
        public byte[] Salt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensagens> Mensagens { get; set; }
    }
}
